### ISSUE TITLE
Incorrect number of neurons in output layer

### ISSUE THREAD

**Issue by flaviu-gostin** [udacity/intro-to-ml-tensorflow#5]
The number of neurons in the output layers should be 2 because there are 2 classes (cats and dogs).
This appears in both the Exercise and the Solution notebooks linked below (couldn't link to the specific line in the Solution notebook):

https://github.com/udacity/intro-to-ml-tensorflow/blob/8199f657e523e48c8ebf7bfa913747588b9d6884/lessons/intro-to-tensorflow/Part_7_Loading_Image_Data_(Exercise).ipynb?short_path=3b94256#L786

https://github.com/udacity/intro-to-ml-tensorflow/blob/8199f657e523e48c8ebf7bfa913747588b9d6884/lessons/intro-to-tensorflow/Part_7_Loading_Image_Data_(Solution).ipynb

**Comment by abhiojha8** [comment]
This is resolved in commit #db7c46c.
